Krypto
Defelo/MorpheusHelper pull request #123
Opened 2021-01-15 22:31 UTC by FlorianJSa

In this commit, the cog CryptoCurrenciesCog was added, which lists the last three price of cryptocurrencies listed on CoinMarketCap above

2021-01-26 18:43 UTC, felbinger requested changes
- move `morpheushelper/models/coinmarketcap.py` from `models` to cog.
- refactor docker workflow (reset to original version)

2021-01-26 18:58 UTC, luwol03 commented
I would suggest to create an extra folder e.g. called `api_models` and put the clever bot api class and the i run code api class 
from #130 there as well to get a clean folder structure because the cogs are imao only for discord classes.

2021-01-26 20:28 UTC, FlorianJSa commented
> I would suggest to create an extra folder e.g. called `api_models` and put the clever bot api class and the i run code api class
> from #130 there as well to get a clean folder structure because the cogs are imao only for discord classes.

This would be a useful folder structure.

2021-02-05 11:00 UTC, Paul-Brauckmann commented on morpheushelper/coinmarketcap.py
> +        return requests.get(url=f"{self.URL}/v1/cryptocurrency/listings/latest", params=parameters, headers=headers)
sollte entsprechend auch Asynchron stattfinden.

2021-02-05 11:00 UTC, Paul-Brauckmann commented on morpheushelper/coinmarketcap.py
> +    def get_cryptocurrencies_list(self):
Die Methode sollte Async sein und im Zweifel nicht den Thread blockieren….

2021-04-03 19:13 UTC, Paul-Brauckmann requested changes
Due to a the restructuring of the Bot this pull reuest is not up to date. Feel free to close this and reopen it in the [cogs-repo](https://github.com/PyDrocsid/cogs).

2021-05-27 13:49 UTC, closed without merging