DC Bot Token Info and DC Bot Token deleter
Defelo/MorpheusHelper pull request #159
Opened 2021-03-03 07:28 UTC by Tert0

**Description**
- A Discord Bot Token info
- A Disocrd Bot Token deleter

**Additional Notes**
Does anyone have a better idea for the info text?

2021-03-03 07:36 UTC, luwol03 commented
Could you send the user the deleted message via PN so that he does not have to rewrite it? Maybe you can even replace the token with `***`.

2021-03-03 08:06 UTC, luwol03 commented
Your regex does not work in all cases.
```
"ODDFOFXUpgf7yEntul5ockCA.OFk6Ph.lmsA54bT0Fux1IpsYvey5XuZk04"
``` 
*(its a fake token)*
this won't be deleted.

2021-03-03 08:23 UTC, Tert0 commented
I have already found and fixed the bug, but have not pushed it yet.

2021-03-03 08:27 UTC, FlorianJSa submitted a review, later dismissed

2021-03-03 16:49 UTC, Paul-Brauckmann requested changes

2021-03-03 16:49 UTC, Paul-Brauckmann commented on morpheushelper/cogs/discord_bot_tokens.py
> +class DiscordBotTokenCog(Cog):
Please consider to create a class var with a compiled version of the regex, like so:
```python
class DiscordBotTokenCog(Cog):
    RE_DC_TOKEN = re.compile(r'[A-Za-z\d]{24}\.[A-Za-z\d]{6}\.[A-Za-z\d\-\_]{27}')
```

2021-03-03 16:49 UTC, Paul-Brauckmann commented on morpheushelper/cogs/discord_bot_tokens.py
> +        if re.match(r'[A-Za-z\d]{24}\.[A-Za-z\d]{6}\.[A-Za-z\d\-\_]{27}', msg.content):
An early return would be nice an save on nested for the rest of the method.
```python
if not self.RE_DC_TOKEN.match(msg.content):
    return

# ...
```

2021-03-03 16:49 UTC, Paul-Brauckmann commented on morpheushelper/cogs/discord_bot_tokens.py
> +            pass
logging would be nice.

2021-03-03 16:49 UTC, Paul-Brauckmann commented on morpheushelper/cogs/discord_bot_tokens.py
> +                pass
logging would be nice.

2021-03-03 17:33 UTC, Paul-Brauckmann requested changes

2021-03-03 17:33 UTC, Paul-Brauckmann commented on morpheushelper/cogs/discord_bot_tokens.py
> +        if tokens := self.RE_DC_TOKEN.findall(msg.content):
An early return would be nice an save on nested for the rest of the method.
```python
if not (tokens := self.RE_DC_TOKEN.findall(msg.content)):
    return

await msg.channel.send(embed=make_embed(msg.author))
# ...
```

2021-03-03 18:47 UTC, Paul-Brauckmann approved these changes

2021-03-05 20:09 UTC, Defelo requested changes

2021-03-05 20:09 UTC, Defelo commented on morpheushelper/cogs/discord_bot_tokens.py
> +    @guild_only()
you can't use this decorator on event handlers

2021-03-05 20:09 UTC, Defelo commented on morpheushelper/cogs/discord_bot_tokens.py
> +        await msg.author.send(embed=make_embed(msg.author))
when deleting a message you should send a different text to explain to the user why the message has been deleted

2021-03-05 20:09 UTC, Defelo commented on translations/en.yml
> +  If another person gets it, the entire bot can be controlled with it!
please improve this text and add information on how to reset the bot token (include a link to the developer portal!)

2021-03-27 09:41 UTC, Paul-Brauckmann approved these changes

2021-04-03 19:12 UTC, Paul-Brauckmann requested changes
Due to a the restructuring of the Bot this pull reuest is not up to date. Feel free to close this and reopen it in the [cogs-repo](https://github.com/PyDrocsid/cogs).

2021-05-27 13:50 UTC, closed without merging