v2.3.0
Defelo/MorpheusHelper pull request #166
Opened 2021-03-09 14:31 UTC by Defelo

2021-03-13 13:46 UTC, FlorianJSa approved these changes, later dismissed

2021-03-14 01:04 UTC, Defelo reviewed
> keine aliase?

@TheCataliasTNT2k

2021-03-14 01:04 UTC, Defelo commented on translations/en.yml
> +alert_channel_hop_set_amount: The new minimum channel hops per minute has been changed.
> hört sich komisch an

@TheCataliasTNT2k

2021-03-14 01:04 UTC, Defelo commented on translations/en.yml
> +alert_channel_hop_log_updated: "**Alerts**\nThe maximum amount of hops has been updated to {}. :white_check_mark:"
> entscheided euch mal für ein von beidem, einmal maximum einmal minimum is doof

@TheCataliasTNT2k

2021-03-14 09:20 UTC, Felix1234-wq commented on morpheushelper/cogs/alert_channel.py
> +        Unsets the alert channel
@4norak

2021-03-14 11:07 UTC, Defelo commented on morpheushelper/cogs/alert_channel.py
> +        Unsets the alert channel
@Felix1234-wq ?

2021-03-14 11:36 UTC, 4norak commented on morpheushelper/cogs/alert_channel.py
> +        Unsets the alert channel
@Felix1234-wq Whomst has awakened the ancient one?

2021-03-16 02:06 UTC, TheCataliasTNT2k requested changes
Alertchannel can be set to a channel without write permissions

2021-03-16 15:49 UTC, TheCataliasTNT2k approved these changes

2021-03-16 15:50 UTC, merged